summary: Accordions Everywhere
value:
  fullscreen: false
  grid:
    - '12':
        fixed: false
        fullHeight: false
        h: 8
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 3
        x: 0
        'y': 0
      id: a
      data:
        id: a
        type: accordionlistcomponent
        actions: []
        componentInput:
          type: static
          value:
            - foo: 1
              header: First
            - foo: 2
              header: Second
            - foo: 3
              header: Third
          fieldType: array
          subFieldType: object
        configuration: {}
        customCss:
          container:
            class: ''
            style: ''
        numberOfSubgrids: 1
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    a-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 1
          x: 0
          'y': 0
        id: b
        data:
          id: b
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections:
              - id: activeIndex
                componentId: a
              - id: result
                componentId: a
            eval: 'Content ${a.result[a.activeIndex].foo}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: false
            style:
              type: static
              value: Body
            tooltip:
              type: static
              value: ''
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: ''
              style: ''
          horizontalAlignment: left
          verticalAlignment: top
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: publisher
  s3_inputs: []
  triggerables_v2: {}
