summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: true
        fullHeight: false
        h: 2
        w: 6
        x: 0
        'y': 0
      id: topbar
      data:
        id: topbar
        type: containercomponent
        actions: []
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 3
        x: 0
        'y': 2
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 2
        x: 0
        'y': 2
      id: a
      data:
        id: a
        type: selectcomponent
        actions: []
        configuration:
          create:
            type: static
            value: false
          defaultValue:
            type: static
          disabled:
            type: static
            value: false
          fullWidth:
            type: static
            value: true
          items:
            type: evalv2
            value:
              - value: foo
                label: Foo
              - value: bar
                label: Bar
            connections:
              - id: result
                componentId: bg_0
            expr: bg_0.result
          nativeHtmlSelect:
            type: static
            value: false
          placeholder:
            type: static
            value: Select an item
          preselectFirst:
            type: static
            value: true
        customCss:
          input:
            class: ''
            style: ''
            tooltip: >-
              https://github.com/rob-balfre/svelte-select/blob/master/docs/theming_variables.md
        onSelect: []
        recomputeIds: []
        verticalAlignment: center
  hiddenInlineScripts:
    - type: runnableByName
      name: Background Runnable 0
      autoRefresh: true
      fields:
        x:
          type: static
          value: null
          fieldType: string
      inlineScript:
        content: '!inline background_runnable_0.inline_script.ts'
        lock: '!inline background_runnable_0.inline_script.lock'
        language: bun
        path: u/alex/newapp/Background_Runnable_0
        schema:
          $schema: 'https://json-schema.org/draft/2020-12/schema'
          type: object
          properties:
            x:
              type: string
              description: ''
              default: null
              originalType: string
          required:
            - x
      recomputeIds: []
      recomputeOnInputChanged: true
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    topbar-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        id: title
        data:
          id: title
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 1
        id: recomputeall
        data:
          id: recomputeall
          type: recomputeallcomponent
          actions: []
          configuration:
            defaultRefreshInterval:
              type: static
              value: '0'
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  allowed_s3_keys: []
  execution_mode: publisher
  s3_inputs: []
  triggerables_v2:
    'bg_0:rawscript/dc2bd5a2b74eb9f1adab8a728d91c37984efba9d7764507a391ef413abf16ccb':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs:
        x: null
