summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: true
        fullHeight: false
        h: 2
        w: 6
        x: 0
        'y': 0
      id: topbar
      data:
        id: topbar
        type: containercomponent
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 20
        w: 12
        x: 0
        'y': 2
      '3':
        fixed: false
        fullHeight: false
        h: 10
        w: 3
        x: 0
        'y': 2
      id: a
      data:
        id: a
        type: aggridcomponent
        actions:
          - id: a_a
            type: buttoncomponent
            componentInput:
              type: runnable
              fields: {}
              fieldType: any
            configuration:
              afterIcon:
                type: static
              beforeIcon:
                type: static
              color:
                type: static
                value: blue
              confirmationModal:
                type: oneOf
                configuration:
                  confirmationModal:
                    description:
                      type: static
                      value: Are you sure?
                    confirmationText:
                      type: static
                      value: Confirm
                    title:
                      type: static
                      value: Title
                  none: {}
                selected: none
              disabled:
                type: static
                value: false
              fillContainer:
                type: static
                value: false
              label:
                type: static
                value: Press me
              onError:
                type: oneOf
                configuration:
                  close:
                    id:
                      type: static
                      value: ''
                  errorOverlay: {}
                  gotoUrl:
                    newTab:
                      type: static
                      value: true
                    url:
                      type: static
                      value: ''
                  open:
                    id:
                      type: static
                      value: ''
                  sendErrorToast:
                    appendError:
                      type: static
                      value: true
                    message:
                      type: static
                      value: An error occured
                  setTab:
                    setTab:
                      type: static
                      value: []
                selected: errorOverlay
              onSuccess:
                type: oneOf
                configuration:
                  clearFiles:
                    id:
                      type: static
                      value: ''
                  close:
                    id:
                      type: static
                      value: ''
                  closeModal:
                    modalId:
                      type: static
                      value: ''
                  gotoUrl:
                    newTab:
                      type: static
                      value: true
                    url:
                      type: static
                      value: ''
                  none: {}
                  open:
                    id:
                      type: static
                      value: ''
                  openModal:
                    modalId:
                      type: static
                      value: ''
                  sendToast:
                    message:
                      type: static
                      value: ''
                  setTab:
                    setTab:
                      type: static
                      value: []
                selected: none
              size:
                type: static
                value: xs2
              triggerOnAppLoad:
                type: static
                value: false
            customCss:
              button:
                class: ''
                style: ''
              container:
                class: ''
                style: ''
            horizontalAlignment: center
            recomputeIds: []
            verticalAlignment: center
          - id: a_b
            type: buttoncomponent
            componentInput:
              type: runnable
              fields: {}
              fieldType: any
            configuration:
              afterIcon:
                type: static
              beforeIcon:
                type: static
              color:
                type: static
                value: blue
              confirmationModal:
                type: oneOf
                configuration:
                  confirmationModal:
                    description:
                      type: static
                      value: Are you sure?
                    confirmationText:
                      type: static
                      value: Confirm
                    title:
                      type: static
                      value: Title
                  none: {}
                selected: none
              disabled:
                type: static
                value: false
              fillContainer:
                type: static
                value: false
              label:
                type: static
                value: Press me
              onError:
                type: oneOf
                configuration:
                  close:
                    id:
                      type: static
                      value: ''
                  errorOverlay: {}
                  gotoUrl:
                    newTab:
                      type: static
                      value: true
                    url:
                      type: static
                      value: ''
                  open:
                    id:
                      type: static
                      value: ''
                  sendErrorToast:
                    appendError:
                      type: static
                      value: true
                    message:
                      type: static
                      value: An error occured
                  setTab:
                    setTab:
                      type: static
                      value: []
                selected: errorOverlay
              onSuccess:
                type: oneOf
                configuration:
                  clearFiles:
                    id:
                      type: static
                      value: ''
                  close:
                    id:
                      type: static
                      value: ''
                  closeModal:
                    modalId:
                      type: static
                      value: ''
                  gotoUrl:
                    newTab:
                      type: static
                      value: true
                    url:
                      type: static
                      value: ''
                  none: {}
                  open:
                    id:
                      type: static
                      value: ''
                  openModal:
                    modalId:
                      type: static
                      value: ''
                  sendToast:
                    message:
                      type: static
                      value: ''
                  setTab:
                    setTab:
                      type: static
                      value: []
                selected: none
              size:
                type: static
                value: xs2
              triggerOnAppLoad:
                type: static
                value: false
            customCss:
              button:
                class: ''
                style: ''
              container:
                class: ''
                style: ''
            horizontalAlignment: center
            recomputeIds: []
            verticalAlignment: center
        componentInput:
          type: static
          value:
            - id: 1
              name: A cell with a long name
              age: 42
            - id: 2
              name: A briefer cell
              age: 84
          fieldType: array
          subFieldType: object
        configuration:
          allEditable:
            type: static
            value: false
          columnDefs:
            type: static
            value:
              - field: id
                flex: 1
              - editable: true
                field: name
                flex: 1
              - field: age
                flex: 1
              - _isActionsColumn: true
                field: __actions__
                flex: 1
                headerName: Actions
                hide: false
          compactness:
            type: static
            value: normal
          customActionsHeader:
            type: static
          extraConfig:
            type: static
            value: {}
          flex:
            type: static
            value: true
          footer:
            type: static
            value: true
          multipleSelectable:
            type: static
            value: false
          pagination:
            type: static
            value: false
          rowIdCol:
            type: static
            value: ''
          rowMultiselectWithClick:
            type: static
            value: true
          selectFirstRowByDefault:
            type: static
            value: true
          wrapActions:
            type: static
            value: false
        customCss:
          container:
            class: ''
            style: ''
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    topbar-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        id: title
        data:
          id: title
          type: textcomponent
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 1
        id: recomputeall
        data:
          id: recomputeall
          type: recomputeallcomponent
          configuration:
            defaultRefreshInterval:
              type: static
              value: '0'
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  allowed_s3_keys: []
  execution_mode: publisher
  s3_inputs: []
  triggerables_v2: {}
