summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: true
        fullHeight: false
        h: 2
        w: 12
        x: 0
        'y': 0
      '3':
        fixed: true
        fullHeight: false
        h: 2
        w: 6
        x: 0
        'y': 0
      id: topbar
      data:
        id: topbar
        type: containercomponent
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 8
        w: 12
        x: 0
        'y': 2
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 3
        x: 0
        'y': 2
      id: a
      data:
        id: a
        type: carousellistcomponent
        componentInput:
          type: static
          value:
            - foo: 1
            - foo: 2
            - foo: 3
            - {}
            - {}
          fieldType: array
          subFieldType: object
        configuration:
          timingFunction:
            type: static
            value: linear
        customCss:
          container:
            class: ''
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 8
        w: 6
        x: 0
        'y': 10
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 2
        x: 1
        'y': 10
      id: b
      data:
        id: b
        type: steppercomponent
        componentInput:
          type: runnable
          fields: {}
          fieldType: any
        configuration: {}
        customCss:
          container:
            class: ''
            style: ''
        numberOfSubgrids: 2
        tabs:
          - First
          - Second
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 2
        x: 6
        'y': 10
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 1
        x: 0
        'y': 10
      id: f
      data:
        id: f
        type: buttoncomponent
        componentInput:
          type: runnable
          autoRefresh: false
          fields: {}
          fieldType: any
          recomputeOnInputChanged: false
          runnable:
            type: runnableByName
            name: Inline Script
            inlineScript:
              content: '!inline inline_script.inline_script.frontend.js'
              language: frontend
              path: frontend script
              suggestedRefreshOn: []
        configuration:
          afterIcon:
            type: static
          beforeIcon:
            type: static
          color:
            type: static
            value: blue
          confirmationModal:
            type: oneOf
            configuration:
              confirmationModal:
                description:
                  type: static
                  value: Are you sure?
                confirmationText:
                  type: static
                  value: Confirm
                title:
                  type: static
                  value: Title
              none: {}
            selected: none
          disabled:
            type: static
            value: false
          fillContainer:
            type: static
            value: false
          label:
            type: static
            value: Press me
          onError:
            type: oneOf
            configuration:
              close:
                id:
                  type: static
                  value: ''
              errorOverlay: {}
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              open:
                id:
                  type: static
                  value: ''
              sendErrorToast:
                appendError:
                  type: static
                  value: true
                message:
                  type: static
                  value: An error occured
              setTab:
                setTab:
                  type: static
                  value: []
            selected: errorOverlay
          onSuccess:
            type: oneOf
            configuration:
              clearFiles:
                id:
                  type: static
                  value: ''
              close:
                id:
                  type: static
                  value: ''
              closeModal:
                modalId:
                  type: static
                  value: ''
              gotoUrl:
                newTab:
                  type: static
                  value: true
                url:
                  type: static
                  value: ''
              none: {}
              open:
                id:
                  type: static
                  value: ''
              openModal:
                modalId:
                  type: static
                  value: ''
              sendToast:
                message:
                  type: static
                  value: ''
              setTab:
                setTab:
                  type: static
                  value: []
            selected: none
          size:
            type: static
            value: xs
          triggerOnAppLoad:
            type: static
            value: false
        customCss:
          button:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
        horizontalAlignment: center
        recomputeIds: []
        verticalAlignment: center
    - '12':
        fixed: false
        fullHeight: false
        h: 1
        w: 3
        x: 6
        'y': 12
      '3':
        fixed: false
        fullHeight: false
        h: 1
        w: 1
        x: 6
        'y': 12
      id: c
      data:
        id: c
        type: textcomponent
        componentInput:
          type: templatev2
          connections:
            - id: currentIndex
              componentId: a
          eval: 'Hello ${a.currentIndex}'
          fieldType: template
        configuration:
          copyButton:
            type: static
            value: false
          disableNoText:
            type: static
            value: false
          style:
            type: static
            value: Body
          tooltip:
            type: static
            value: ''
        customCss:
          container:
            class: ''
            style: ''
          text:
            class: ''
            style: ''
        horizontalAlignment: left
        verticalAlignment: top
    - '12':
        fixed: false
        fullHeight: false
        h: 8
        w: 6
        x: 6
        'y': 13
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 2
        x: 0
        'y': 18
      id: e
      data:
        id: e
        type: tabscomponent
        configuration:
          tabsKind:
            type: static
            value: tabs
        customCss:
          allTabs:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
          selectedTab:
            class: ''
            style: ''
          tabRow:
            class: ''
            style: ''
        disabledTabs:
          - type: static
            value: false
            fieldType: boolean
          - type: static
            value: false
            fieldType: boolean
        numberOfSubgrids: 2
        tabs:
          - First tab
          - Second tab
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  mobileViewOnSmallerScreens: false
  norefreshbar: false
  subgrids:
    a-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 10
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 10
          w: 3
          x: 0
          'y': 0
        id: d
        data:
          id: d
          type: aggridcomponent
          actions: []
          componentInput:
            type: static
            value:
              - id: 1
                name: A cell with a long name
                age: 42
              - id: 2
                name: A briefer cell
                age: 84
            fieldType: array
            subFieldType: object
          configuration:
            allEditable:
              type: static
              value: false
            columnDefs:
              type: static
              value:
                - field: id
                  flex: 1
                - editable: true
                  field: name
                  flex: 1
                - field: age
                  flex: 1
            compactness:
              type: static
              value: normal
            customActionsHeader:
              type: static
            extraConfig:
              type: static
              value: {}
            flex:
              type: static
              value: true
            footer:
              type: static
              value: true
            multipleSelectable:
              type: static
              value: false
            pagination:
              type: static
              value: false
            rowIdCol:
              type: static
              value: ''
            rowMultiselectWithClick:
              type: static
              value: true
            selectFirstRowByDefault:
              type: static
              value: true
            wrapActions:
              type: static
              value: false
          customCss:
            container:
              class: ''
              style: ''
    b-0: []
    b-1: []
    e-0: []
    e-1: []
    topbar-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          'y': 0
        id: title
        data:
          id: title
          type: textcomponent
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          'y': 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          'y': 1
        id: recomputeall
        data:
          id: recomputeall
          type: recomputeallcomponent
          configuration:
            defaultRefreshInterval:
              type: static
              value: '0'
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  allowed_s3_keys: []
  execution_mode: publisher
  s3_inputs: []
  triggerables_v2:
    'f:rawscript/6bf9336a06e70b1a65a93efd72290287264f5a1bb2d1e4773ae4f0b8327160c3':
      allow_user_resources: []
      one_of_inputs: {}
      static_inputs: {}
